# Generated by Django 4.1.3 on 2023-03-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('yes_amount', models.IntegerField()),
                ('no_amount', models.IntegerField()),
                ('chance_win', models.IntegerField()),
                ('done', models.CharField(choices=[('start', 'start'), ('done', 'done')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Myuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=12)),
                ('curr_amount', models.IntegerField(default=25)),
                ('added_amount', models.IntegerField(default=0)),
            ],
        ),
    ]
