# Generated by Django 4.1.3 on 2023-03-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.context')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.myuser')),
            ],
        ),
    ]
