# Generated by Django 4.1.3 on 2023-03-18 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
