# Generated by Django 4.1.3 on 2023-03-18 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_context_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='middle_line',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
