# Generated by Django 4.1.3 on 2023-03-18 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_context_middle_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='win_chance',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
