# Generated by Django 4.1.3 on 2023-03-18 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_context_win_chance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_context',
            name='option',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
