# Generated by Django 4.1.3 on 2023-03-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_context_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='who_win',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=20, null=True),
        ),
    ]
